name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  persian_time_selector:
    path : ../
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  

 
  assets:
    - assets/images/

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/Dana.ttf
          weight: 200
