name: persian_time_selector
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 3.0.1

homepage: https://github.com/mortezasojodi/persian_time_selector

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

