name: persian_time_selector
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 3.8.1

homepage: https://github.com/mortezasojodi/persian_time_selector

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

